### ISSUE TITLE
Cache everything?

### ISSUE THREAD

**Issue by Leksat** [jetify-com/devbox-install-action#57]
If https://releases.jetpack.io/devbox/stable/version or https://get.jetify.com/devbox is down, the action fails.

I use `enable-cache: 'true'`, yet it does not help if jetpack.io errors. Maybe it's possible to make the cache more aggressive?

**Comment by LucilleH** [comment]
@Leksat The devbox cli should be already cached if you specify `devbox-version: <version>`.

PS: The unfortunate thing happened - https://releases.jetpack.io/devbox/stable/version was down at that time (there was an S3 outage)

**Comment by Leksat** [comment]
Whoops, I missed `if` in the `Install devbox cli` step 🙈 

Just checked, it works like a charm with `devbox-version`. Thanks!
